#!/usr/bin/env python3
"""Regenerate the committed static OpenAPI specification for the AI service.

``main.py`` serves ``/openapi.json`` at runtime via FastAPI's built-in
support.  This script re-derives that exact document from the live app
object and writes it to ``openapi.json`` in the service directory, so the
checked-in spec can never silently drift from the route/schema source.

Usage (from the repo root or ``app/ai-service``)::

    python app/ai-service/scripts/generate_openapi.py
    # or
    cd app/ai-service && python scripts/generate_openapi.py

CI (``.github/workflows/ai-service-ci.yml`` -> ``openapi-drift`` job) runs
this script and fails the build if ``git diff --exit-code`` reports a change
to ``app/ai-service/openapi.json``.  When the API surface changes,
regenerate and commit the new spec in the same PR.
"""

import json
import sys
from pathlib import Path

# Make ``main`` importable whether this script is invoked from the repo
# root or directly from ``app/ai-service``.
SERVICE_DIR = Path(__file__).resolve().parent.parent
if str(SERVICE_DIR) not in sys.path:
    sys.path.insert(0, str(SERVICE_DIR))

# Importing the module is enough: building the OpenAPI document only needs
# the router registrations; the lifespan (and its side effects) never runs.
from main import app  # noqa: E402  (sys.path setup must run first)

OUTPUT_PATH = SERVICE_DIR / "openapi.json"


def main() -> int:
    spec = app.openapi()
    # ``sort_keys=True`` keeps the committed document stable and diffs
    # minimal regardless of FastAPI/Python dict-ordering changes.
    payload = json.dumps(spec, indent=2, sort_keys=True) + "\n"
    # Force LF endings so the generated bytes are identical on Windows and
    # Linux (CI): CI's drift check compares this file byte-for-byte against
    # the committed copy.
    OUTPUT_PATH.write_text(payload, encoding="utf-8", newline="\n")
    print(f"Wrote OpenAPI spec ({len(payload)} bytes) to {OUTPUT_PATH}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
