packages:
  - 'app/*'
allowBuilds:
  '@parcel/watcher': false
  '@prisma/engines': false
  '@scarf/scarf': false
  '@sentry/cli': false
  '@swc/core': false
  core-js: true
  msgpackr-extract: false
  prisma: false
  protobufjs: true
  sharp: false
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@aws-sdk/client-s3@3.1119.0'
