'use client';

import { useQuery } from '@tanstack/react-query';
import type {
  ContractRegistryResponse,
  ContractRegistryEntry,
  ContractRegistryResult,
  ContractRegistryState,
  ContractNetworkDeployment,
} from '@/types/contract-registry';

/**
 * The registry is a deterministic JSON artifact generated by
 * `app/onchain/scripts/generate-registry.py` ("for backend/frontend
 * consumption") and served as a static file from the frontend origin
 * (`public/contract-registry.json`). It is not a backend API endpoint, so
 * this hook fetches it directly — no auth required, cacheable.
 */
const REGISTRY_URL = '/contract-registry.json';

const POLL_INTERVAL_MS = 60_000;

async function fetchContractRegistry(): Promise<ContractRegistryResponse> {
  const controller = new AbortController();
  const timeoutId = setTimeout(() => controller.abort(), 10_000);

  try {
    const response = await fetch(REGISTRY_URL, {
      signal: controller.signal,
      cache: 'no-store',
    });

    if (!response.ok) {
      throw new Error(`Contract registry endpoint returned ${response.status}`);
    }

    return response.json() as Promise<ContractRegistryResponse>;
  } finally {
    clearTimeout(timeoutId);
  }
}

function deriveState(
  hasData: boolean,
  isLoading: boolean,
  isError: boolean,
): ContractRegistryState {
  if (isLoading) return 'loading';
  if (isError) return 'error';
  if (hasData) return 'ready';
  return 'error';
}

export interface ContractRegistryMatch {
  name: string;
  network: string;
  deployment: ContractNetworkDeployment;
}

export function useContractRegistry(): ContractRegistryResult & {
  getContract: (name: string, network?: string) => ContractRegistryEntry | null;
  findByContractId: (contractId: string) => ContractRegistryMatch | null;
} {
  const { data, error, isLoading, dataUpdatedAt } = useQuery<
    ContractRegistryResponse,
    Error
  >({
    queryKey: ['contract-registry'],
    queryFn: fetchContractRegistry,
    refetchInterval: POLL_INTERVAL_MS,
    refetchIntervalInBackground: true,
    retry: 1,
    staleTime: POLL_INTERVAL_MS,
  });

  const state = deriveState(!!data, isLoading, !!error);
  const lastChecked = dataUpdatedAt ? new Date(dataUpdatedAt) : null;

  const getContract = (name: string, network?: string): ContractRegistryEntry | null => {
    if (!data?.contracts?.[name]) return null;
    const entry = data.contracts[name];
    if (!network) return entry;
    return entry.networks?.[network] ? entry : null;
  };

  /** Reverse lookup: which contract/network a deployed contract ID belongs to. */
  const findByContractId = (contractId: string): ContractRegistryMatch | null => {
    if (!contractId || !data?.contracts) return null;
    for (const [name, entry] of Object.entries(data.contracts)) {
      for (const [network, deployment] of Object.entries(entry.networks ?? {})) {
        if (deployment.contract_id === contractId) {
          return { name, network, deployment };
        }
      }
    }
    return null;
  };

  return {
    state,
    data: data ?? null,
    error: error ?? null,
    lastChecked,
    getContract,
    findByContractId,
  };
}
