'use client';

import type { RefObject } from 'react';
import { ChevronLeft, ChevronRight, Download, LoaderCircle } from 'lucide-react';
import type { ReportSource, ValidationResult } from '@/lib/csv-validation';
import { ValidationReportPanel } from './ValidationReportPanel';

interface Step3ValidationProps {
  result: ValidationResult;
  headers: string[];
  isValidating: boolean;
  canProceed: boolean;
  isDownloadingReport?: boolean;
  lastReportSource?: ReportSource | null;
  headingRef?: RefObject<HTMLHeadingElement | null>;
  onBack: () => void;
  onNext: () => void;
  onDownloadReport: () => void;
}

export function Step3Validation({
  result,
  headers,
  isValidating,
  canProceed,
  isDownloadingReport = false,
  lastReportSource = null,
  headingRef,
  onBack,
  onNext,
  onDownloadReport,
}: Step3ValidationProps) {
  const hasBlockingErrors = result.summary.errorRows > 0;

  return (
    <div className="space-y-6">
      <div className="flex flex-wrap items-start justify-between gap-4">
        <div className="space-y-2">
          <h2 ref={headingRef} tabIndex={-1} className="text-2xl font-semibold text-slate-900 dark:text-slate-50 focus:outline-none">Step 3: Resolve validation issues</h2>
          <p className="text-sm text-slate-600 dark:text-slate-300">
            Search and filter row-level warnings and errors before final confirmation. Errors block import until the source file is corrected and re-uploaded.
          </p>
        </div>

        <div className="space-y-1">
          <button
            type="button"
            onClick={onDownloadReport}
            disabled={isDownloadingReport}
            className="inline-flex items-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"
          >
            {isDownloadingReport ? <LoaderCircle className="h-4 w-4 animate-spin" /> : <Download className="h-4 w-4" />}
            {isDownloadingReport ? 'Preparing report…' : 'Download report'}
          </button>
          {lastReportSource && !isDownloadingReport && (
            <p className="text-right text-xs text-slate-500 dark:text-slate-400">
              {lastReportSource === 'backend'
                ? 'Last report generated by the backend.'
                : 'Last report generated locally (backend unavailable).'}
            </p>
          )}
        </div>
      </div>

      <div className="grid gap-4 sm:grid-cols-4">
        <div className="rounded-xl border border-slate-200 bg-slate-50 p-4 dark:border-slate-800 dark:bg-slate-950">
          <p className="text-xs uppercase tracking-[0.18em] text-slate-500 dark:text-slate-400">Total rows</p>
          <p className="mt-2 text-2xl font-semibold text-slate-900 dark:text-slate-50">{result.summary.totalRows}</p>
        </div>
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-4 dark:border-emerald-900/50 dark:bg-emerald-950/30">
          <p className="text-xs uppercase tracking-[0.18em] text-emerald-700 dark:text-emerald-300">Valid</p>
          <p className="mt-2 text-2xl font-semibold text-emerald-800 dark:text-emerald-200">{result.summary.validRows}</p>
        </div>
        <div className="rounded-xl border border-amber-200 bg-amber-50 p-4 dark:border-amber-900/50 dark:bg-amber-950/30">
          <p className="text-xs uppercase tracking-[0.18em] text-amber-700 dark:text-amber-300">Warnings</p>
          <p className="mt-2 text-2xl font-semibold text-amber-800 dark:text-amber-200">{result.summary.warningRows}</p>
        </div>
        <div className="rounded-xl border border-rose-200 bg-rose-50 p-4 dark:border-rose-900/50 dark:bg-rose-950/30">
          <p className="text-xs uppercase tracking-[0.18em] text-rose-700 dark:text-rose-300">Errors</p>
          <p className="mt-2 text-2xl font-semibold text-rose-800 dark:text-rose-200">{result.summary.errorRows}</p>
        </div>
      </div>

      <div
        className={`rounded-xl border px-4 py-3 text-sm ${
          hasBlockingErrors
            ? 'border-rose-200 bg-rose-50 text-rose-700 dark:border-rose-900/50 dark:bg-rose-950/30 dark:text-rose-300'
            : 'border-emerald-200 bg-emerald-50 text-emerald-700 dark:border-emerald-900/50 dark:bg-emerald-950/30 dark:text-emerald-300'
        }`}
      >
        {hasBlockingErrors
          ? 'Some rows still have blocking errors. Download the report, correct the CSV, then upload the revised file to continue.'
          : 'No blocking errors remain. You can continue to final confirmation.'}
      </div>

      <ValidationReportPanel rows={result.rows} headers={headers} />

      <div className="flex flex-wrap items-center justify-between gap-3">
        <button
          type="button"
          onClick={onBack}
          disabled={isValidating}
          className="inline-flex min-w-28 items-center justify-center gap-2 rounded-lg border border-slate-300 bg-white px-4 py-2.5 text-sm font-medium text-slate-700 transition hover:bg-slate-50 disabled:cursor-not-allowed disabled:opacity-50 dark:border-slate-700 dark:bg-slate-900 dark:text-slate-200 dark:hover:bg-slate-800"
        >
          <ChevronLeft className="h-4 w-4" />
          Back
        </button>

        <button
          type="button"
          onClick={onNext}
          disabled={!canProceed || hasBlockingErrors}
          className="inline-flex min-w-32 items-center justify-center gap-2 rounded-lg bg-blue-600 px-4 py-2.5 text-sm font-medium text-white transition hover:bg-blue-700 disabled:cursor-not-allowed disabled:opacity-50"
        >
          Continue
          <ChevronRight className="h-4 w-4" />
        </button>
      </div>
    </div>
  );
}
