'use client';

import React, { useState } from 'react';
import { useTranslations } from 'next-intl';
import {
  Check,
  ChevronDown,
  ChevronUp,
  Clock,
  Copy,
  ExternalLink,
  FileCode,
  Shield,
} from 'lucide-react';
import { useContractRegistry } from '@/hooks/useContractRegistry';
import { buildExplorerUrl } from '@/lib/explorer';

interface ContractRegistryPanelProps {
  /** Optional DOM id, e.g. so other pages can deep-link to this panel. */
  id?: string;
  className?: string;
  /** Whether the deployment details are expanded on first render. */
  defaultExpanded?: boolean;
}

/**
 * Shared "source of truth" panel for the deployed contract registry
 * (`public/contract-registry.json`, generated by
 * `app/onchain/scripts/generate-registry.py`). Surfaces active contract
 * IDs, network labels, and deployment metadata so admin and receipt
 * surfaces don't each hardcode their own copy.
 */
export function ContractRegistryPanel({
  id,
  className = '',
  defaultExpanded = true,
}: ContractRegistryPanelProps) {
  const t = useTranslations('demoChecklist');
  const { state, data, error } = useContractRegistry();
  const [copiedId, setCopiedId] = useState<string | null>(null);
  const [expanded, setExpanded] = useState(defaultExpanded);

  const copyId = async (rowId: string, contractId: string) => {
    try {
      await navigator.clipboard.writeText(contractId);
      setCopiedId(rowId);
      setTimeout(() => setCopiedId(null), 2000);
    } catch {
      /* clipboard unavailable */
    }
  };

  if (state === 'loading') {
    return (
      <div
        id={id}
        className={`rounded-xl border border-slate-200 bg-white p-5 dark:border-slate-800 dark:bg-slate-900 space-y-3 ${className}`}
      >
        <div className="flex items-center gap-2">
          <FileCode size={18} className="text-slate-500 animate-pulse" />
          <h3 className="text-sm font-semibold">{t('registryTitle')}</h3>
        </div>
        <p className="text-xs text-slate-500 dark:text-slate-400">
          {t('registryLoading')}
        </p>
      </div>
    );
  }

  if (state === 'error' || !data) {
    return (
      <div
        id={id}
        className={`rounded-xl border border-red-200 bg-red-50/50 p-5 dark:border-red-900/50 dark:bg-red-950/20 space-y-2 ${className}`}
      >
        <div className="flex items-center gap-2">
          <FileCode size={18} className="text-red-500" />
          <h3 className="text-sm font-semibold text-red-700 dark:text-red-400">
            {t('registryTitle')}
          </h3>
        </div>
        <p className="text-xs text-red-600 dark:text-red-400">
          {error?.message || t('registryError')}
        </p>
      </div>
    );
  }

  return (
    <div
      id={id}
      className={`rounded-xl border border-slate-200 bg-white dark:border-slate-800 dark:bg-slate-900 ${className}`}
    >
      <button
        type="button"
        onClick={() => setExpanded((prev) => !prev)}
        className="w-full flex items-start justify-between gap-2 p-5 text-left"
        aria-expanded={expanded}
      >
        <div className="flex items-center gap-2">
          <div className="p-1.5 bg-slate-100 dark:bg-slate-800 rounded-lg">
            <FileCode size={16} className="text-slate-600 dark:text-slate-400" />
          </div>
          <div>
            <h3 className="text-sm font-semibold">{t('registryTitle')}</h3>
            <p className="text-[11px] text-slate-500 dark:text-slate-400 max-w-xs leading-relaxed">
              {t('registrySubtitle')}
            </p>
          </div>
        </div>
        {expanded ? (
          <ChevronUp size={16} className="text-slate-400 shrink-0 mt-1" />
        ) : (
          <ChevronDown size={16} className="text-slate-400 shrink-0 mt-1" />
        )}
      </button>

      {expanded && (
        <div className="px-5 pb-5 space-y-4">
          <dl className="grid grid-cols-2 gap-x-3 gap-y-1.5 text-[11px]">
            <dt className="text-slate-500 dark:text-slate-400 font-medium">
              {t('registrySchemaVersion')}
            </dt>
            <dd className="font-mono text-slate-700 dark:text-slate-300">
              v{data.schema_version}
            </dd>
            <dt className="text-slate-500 dark:text-slate-400 font-medium">
              {t('registryGenerated')}
            </dt>
            <dd className="text-slate-700 dark:text-slate-300">
              {new Date(data.generated_at).toLocaleString()}
            </dd>
          </dl>

          <div className="space-y-3">
            {Object.entries(data.contracts).map(([name, entry]) => {
              const networks = Object.entries(entry.networks);
              return (
                <div
                  key={name}
                  className="rounded-lg border border-slate-200 dark:border-slate-800 bg-slate-50/70 dark:bg-slate-950/40 p-3 space-y-2.5"
                >
                  <div className="flex items-center justify-between">
                    <div className="flex items-center gap-2">
                      <Shield size={14} className="text-blue-500" />
                      <span
                        className="text-xs font-semibold text-slate-800 dark:text-slate-200 font-mono"
                        title={t('registryContract')}
                      >
                        {name}
                      </span>
                    </div>
                    <span
                      className="text-[10px] px-1.5 py-0.5 rounded bg-blue-100 dark:bg-blue-900/40 text-blue-700 dark:text-blue-400 font-mono"
                      title={t('registryCrateVersion')}
                    >
                      crate v{entry.version}
                    </span>
                  </div>

                  {networks.length === 0 ? (
                    <p className="text-[11px] text-slate-500 dark:text-slate-400 italic">
                      {t('registryNoDeployments')}
                    </p>
                  ) : (
                    <div className="space-y-2">
                      {networks.map(([network, dep]) => {
                        const rowId = `${name}-${network}`;
                        const isCopied = copiedId === rowId;
                        return (
                          <div
                            key={network}
                            className="rounded-md bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 p-2.5 space-y-1.5"
                          >
                            <div className="flex items-center justify-between">
                              <span
                                className="text-[10px] px-1.5 py-0.5 rounded font-semibold bg-slate-100 text-slate-600 dark:bg-slate-800 dark:text-slate-300"
                                title={t('registryNetwork')}
                              >
                                {network.toUpperCase()}
                              </span>
                              <span
                                className="text-[10px] text-slate-500 dark:text-slate-400 font-mono"
                                title={t('registryDeployedVersion')}
                              >
                                v{dep.version}
                              </span>
                            </div>
                            <div className="flex items-center justify-between gap-2">
                              <a
                                href={buildExplorerUrl('contract', dep.contract_id, network)}
                                target="_blank"
                                rel="noopener noreferrer"
                                title={dep.contract_id}
                                className="text-[10px] font-mono text-blue-600 hover:underline dark:text-blue-400 truncate flex items-center gap-1"
                              >
                                {dep.contract_id.slice(0, 10)}…{dep.contract_id.slice(-8)}
                                <ExternalLink size={10} className="shrink-0" />
                              </a>
                              <button
                                onClick={() => copyId(rowId, dep.contract_id)}
                                className="p-1 rounded hover:bg-slate-100 dark:hover:bg-slate-800 transition-colors shrink-0"
                                title={t('registryCopyId')}
                                aria-label={`${t('registryCopyId')}: ${name} (${network})`}
                              >
                                {isCopied ? (
                                  <Check size={12} className="text-green-500" />
                                ) : (
                                  <Copy size={12} className="text-slate-400 hover:text-slate-600 dark:hover:text-slate-300" />
                                )}
                              </button>
                            </div>
                            <div
                              className="text-[10px] text-slate-500 dark:text-slate-400 flex items-center gap-1"
                              title={t('registryDeployedAt')}
                            >
                              <Clock size={10} />
                              {dep.deployed_at}
                            </div>
                            <div className="text-[10px] text-slate-500 dark:text-slate-400 flex items-center justify-between gap-2">
                              <span>{t('registryWasmHash')}</span>
                              <code className="font-mono truncate" title={dep.wasm_hash}>
                                {dep.wasm_hash.slice(0, 8)}…{dep.wasm_hash.slice(-6)}
                              </code>
                            </div>
                          </div>
                        );
                      })}
                    </div>
                  )}
                </div>
              );
            })}
          </div>
        </div>
      )}
    </div>
  );
}
